Added dvbcdr python package and intercom submodule
leonard-de-vinci/DaVinciBot-CDR pull request #2
Opened 2021-09-19 16:56 UTC by th0m4s

This pull request adds the base of the `dvbcdr` python package with its first two submodules, `utils` and `intercom`.

## `utils`
`utils` contains methods and classes which are intented to be used across the whole project like math and crypto methods.
This submodule currently includes the `crc24` tools for the `intercom` submodule and *thread safe* classes like `ThreadSafeDict` and `DataEvent` (using Python `threading.Event` with data argument).

## `intercom`
`intercom` contains the library used to communicate between processed and even devices with UDP multicast packets.
Each topic is assigned an IP address inside the range `224.0.0.0/8` using the `crc24` util method.

2021-09-21 22:14 UTC, Zax-code commented on python_packages/dvbcdr/intercom/intercom.py
> +        self.publish(Message(topic, message_data))
![image](https://user-images.githubusercontent.com/67737332/134254700-9251c263-e1c4-494f-9642-56cab7a3c65d.png)

Petit détail mais pour des soucis de compréhension il est préférable de définir la fct avant de l'utiliser, le reste est plutôt compréhensible (en s'appuyant sur les docs des différentes bibliothèques utilisées)

2021-09-21 22:24 UTC, Zax-code requested changes, later dismissed
Tout est bon pour moi tout est compréhensible, j'ai du faire quelques recherches mais je pense que si j'avais été plus familier avec les bibliothèques utilisées ça aurait été compréhensible directement. Le seul changement que je ferais est celui que j'ai commenté dans intercom.py, au delà de ça c'est approuvé pour ma part

2021-09-23 07:06 UTC, COLVERTYETY commented on python_packages/dvbcdr/intercom/intercom.py
> +    def __get_topic_info(self, topic) -> Tuple[int, str]:
@Zax-code  tu peux laisser des commentaires directement sur les lignes de codes au lieu de prendre un screenshot

2021-09-23 07:10 UTC, COLVERTYETY commented on python_packages/dvbcdr/intercom/intercom.py
> +    def __get_topic_info(self, topic) -> Tuple[int, str]:
je remarque qu tu es déja au courant
nice

2021-09-23 07:10 UTC, COLVERTYETY commented
LGTM

2021-09-23 07:10 UTC, COLVERTYETY commented
LGTM

2021-10-01 14:36 UTC, th0m4s commented on python_packages/dvbcdr/intercom/intercom.py
> +    def __get_topic_info(self, topic) -> Tuple[int, str]:
Corrigé par le commit 215737a

2021-10-01 14:38 UTC, th0m4s commented on python_packages/dvbcdr/intercom/intercom.py
> +        self.publish(Message(topic, message_data))
Corrigé par le commit 215737a

2021-10-23 14:01 UTC, Zax-code requested changes
J'ai laissé 2 commentaires sur la fonction qui donne l'arrondi avec les sig fig (significant figures) je pense que tu trouvera la solution tout seul pour corriger (rien de compliqué) mais si besoin dis moi.

2021-10-23 14:01 UTC, Zax-code commented on python_packages/dvbcdr/utils/maths.py
> +            if str_value[i] == "0":
Et s'il y a un nombre dont la partie entière n'est pas nulle mais qui a quand même des 0 après la virgule ?
Exemple : 1.008 a 4 chiffres significatifs, pourtant si j'en demande 2 avec cette fonction on obtiendrait 1.008 puisque des 0 suivent la virgule
![image](https://user-images.githubusercontent.com/67737332/138559307-93138985-d5c6-4aa0-9422-f71822e24766.png)

![image](https://user-images.githubusercontent.com/67737332/138559314-fdcb8f9d-4608-47c5-a84c-38fd71a1f3df.png)


Pour + de tests un lien te donnant les chiffres significatifs des nombres entrés avec leur arrondi à des sig fig + petits : https://en.intl.chemicalaid.com/tools/sigfigscalculator.php?expression=1.008&round=end&direction=half_even

2021-10-23 14:01 UTC, Zax-code commented on python_packages/dvbcdr/utils/maths.py
> +        number = int(number * multiplier) / multiplier
Pas d'arrondis ? Si 1.666 est arrondi à 2 sig fig tu dois obtenir 1.7 pas 1.6 (calcules juste un sig fig supplémentaire pour savoir si tu dois augmenter le dernier nombre)

2022-01-19 11:56 UTC, closed without merging